# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30b6576a3be8df2df347a69b587157a8020609aef51d23a3b3fa737c4e36f635e07c47e44989d8308252b5ed861e24d5b5c2f01483db85a8c0aedb26f8323b2d

test:
  secret_key_base: df6ce32b8019ed9b86308f37ece74155103d62a9d450dafb241ac22e4f6ac0bce66276b653e6b2793a7929d07a716479beaf2a9e1fad2c8f5541e451dedb06ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
